@startuml US15_CD
skinparam classAttributeIconSize 0
hide circle
hide methods

class Administrator {
}

class EmployeeContainer {
}

class RoleContainer {
}

class Employee {
    - id
    - name
    - phoneNumber
    - email
    - citizenCardNumber
}

class Role {
    - designation
}

class ListEmployeeByRoleView {
}

class ListEmployeeByRoleController {
}

Administrator "1" -down- "1" EmployeeContainer : manages >
Administrator "1" -down- "1" RoleContainer : manages >

EmployeeContainer "1" -right- "0..*" Employee : contains >
RoleContainer "1" -left- "0..*" Role : contains >

Employee "0..*" -up- "1" Role : has a >

ListEmployeeByRoleView ..> ListEmployeeByRoleController : uses
ListEmployeeByRoleController ..> Administrator : uses

@enduml