@startuml US15_DomainModel
skinparam classAttributeIconSize 0
hide circle
hide methods

class "DGS Administrator" {
}

class Employee {
    - name
    - postal_address
    - phone_number
    - email
}

class Nurse {
}

class Receptionist {
}

"DGS Administrator" "1" -right-- "0..*" Employee : manages >

Nurse --|> Employee
Receptionist --|> Employee

@enduml