@startuml
autonumber

actor "Receptionist" as Rec
participant ":RegisterArrivalUI" as UI
participant ":RegisterArrivalController" as CTRL
participant ":ArrivalService" as SVC
participant ":AppointmentRepository" as AppRepo
participant ":VaccinationCenterRepository" as VCRepo
participant "center: VaccinationCenter" as CENTER
participant "waitingRoom: WaitingRoom" as ROOM
participant "appointment: Appointment" as APP
participant "arrival: Arrival" as ARRIVAL
participant "dto: AppointmentDTO" as DTO
participant ":AppointmentMapper" as MAPPER

activate Rec
Rec -> UI : asks to register arrival
activate UI

UI --> Rec : asks for SNS User Number
deactivate UI

Rec -> UI : provides SNS User Number
activate UI

UI -> CTRL : getAppointment(snsNumber)
activate CTRL

CTRL -> SVC : getAppointment(snsNumber)
activate SVC

' O Serviço procura agendamentos para hoje para este utente
SVC -> AppRepo : findTodayAppointment(snsNumber)
activate AppRepo
AppRepo --> SVC : appointment
deactivate AppRepo

SVC -> MAPPER : toDTO(appointment)
activate MAPPER
MAPPER --> SVC : dto
deactivate MAPPER

SVC --> CTRL : dto
deactivate SVC

CTRL --> UI : dto
deactivate CTRL

UI --> Rec : shows details and asks confirmation
deactivate UI

Rec -> UI : confirms arrival
activate UI

UI -> CTRL : createArrival()
activate CTRL

CTRL -> SVC : registerArrival(dto.id)
activate SVC

' Recuperar o objeto de domínio appointment
SVC -> AppRepo : findById(dto.id)
activate AppRepo
AppRepo --> SVC : appointment
deactivate AppRepo

' Recuperar o centro atual
SVC -> VCRepo : getCurrentCenter()
activate VCRepo
VCRepo --> SVC : center
deactivate VCRepo

SVC -> CENTER : getWaitingRoom()
activate CENTER
CENTER --> SVC : waitingRoom
deactivate CENTER

' Criar a chegada (Arrival)
SVC -> ARRIVAL** : create(appointment)

' Adicionar à sala de espera
SVC -> ROOM : addArrival(arrival)
activate ROOM
deactivate ROOM

' Mudar o estado do agendamento para ARRIVED
SVC -> APP : arrive()
activate APP
deactivate APP

SVC --> CTRL : success
deactivate SVC

CTRL --> UI : success
deactivate CTRL

UI --> Rec : displays operation success
deactivate UI

deactivate Rec
@enduml