@startuml
skinparam classAttributeIconSize 0

package "UI" {
  class RegisterArrivalUI {
  }
}

package "Core" {

  package "Controller" {
    class RegisterArrivalController {
      + getAppointment(snsNumber: String): AppointmentDTO
      + registerArrival(): boolean
    }
  }

  package "Service" {
    class ArrivalService {
      + getAppointment(snsNumber: String): AppointmentDTO
      + registerArrival(appointmentId: String): boolean
    }
  }

  package "Domain" {
    package "Model" {
      class VaccinationCenter {
        + getWaitingRoom(): WaitingRoom
      }
      class WaitingRoom {
        + addArrival(arrival: Arrival): boolean
      }
      class Arrival {
        - arrivalTime: DateTime
        + create(appointment: Appointment)
      }
      class Appointment {
        - state: AppointmentState
        + arrive(): void
      }
      class SNSUser {}
    }

    package "Repository" {
      class AppointmentRepository {
        + findTodayAppointment(snsNumber: String): Appointment
        + findById(id: String): Appointment
      }
      class VaccinationCenterRepository {
        + getCurrentCenter(): VaccinationCenter
      }
    }
  }

  package "DTO" {
    class AppointmentDTO {
      - id
      - snsUserNumber
      - date
      - time
    }
  }

  package "Mapper" {
    class AppointmentMapper {
      + toDTO(app: Appointment): AppointmentDTO
    }
  }
}

RegisterArrivalUI ..> RegisterArrivalController
RegisterArrivalUI ..> AppointmentDTO

RegisterArrivalController ..> ArrivalService
RegisterArrivalController ..> AppointmentDTO

ArrivalService ..> AppointmentRepository
ArrivalService ..> VaccinationCenterRepository
ArrivalService ..> VaccinationCenter
ArrivalService ..> WaitingRoom
ArrivalService ..> Arrival
ArrivalService ..> Appointment
ArrivalService ..> AppointmentMapper

AppointmentMapper ..> AppointmentDTO
AppointmentMapper ..> Appointment

VaccinationCenter "1" --> "1" WaitingRoom : has
WaitingRoom "1" --> "*" Arrival : contains
Arrival "1" --> "1" Appointment : relates to

@enduml