@startuml
autonumber

actor "Nurse" as Nurse
participant ":ConsultWaitingRoomUI" as UI
participant ":ConsultWaitingRoomController" as CTRL
participant ":WaitingRoomService" as SVC
participant ":VaccinationCenterRepository" as VCRepo
participant "center: VaccinationCenter" as CENTER
participant "waitingRoom: WaitingRoom" as ROOM
participant ":AppointmentMapper" as MAPPER
participant "listDTO: List<AppointmentDTO>" as LIST_DTO

activate Nurse
Nurse -> UI : asks to consult the waiting room
activate UI

UI -> CTRL : getWaitingList()
activate CTRL

CTRL -> SVC : getWaitingList()
activate SVC

' 1. Service obtém o Centro de Vacinação atual (assumindo contexto do utilizador logado)
SVC -> VCRepo : getCurrentCenter()
activate VCRepo
VCRepo --> SVC : center
deactivate VCRepo

' 2. Service pede a sala de espera ao centro
SVC -> CENTER : getWaitingRoom()
activate CENTER
CENTER --> SVC : waitingRoom
deactivate CENTER

' 3. Service pede a lista de agendamentos (que estão na sala de espera)
SVC -> ROOM : getAppointments()
activate ROOM
ROOM --> SVC : appointmentList
deactivate ROOM

' 4. Service converte a lista de objetos de domínio para DTOs
SVC -> MAPPER : toDTOList(appointmentList)
activate MAPPER
MAPPER -> LIST_DTO** : create()
MAPPER --> SVC : listDTO
deactivate MAPPER

SVC --> CTRL : listDTO
deactivate SVC

CTRL --> UI : listDTO
deactivate CTRL

UI --> Nurse : shows the list of users waiting
deactivate UI

deactivate Nurse
@enduml