@startuml
autonumber
actor "Nurse" as Nurse
participant ":System" as System

activate Nurse

Nurse -> System : asks to consult the waiting room
activate System
System --> Nurse : displays the list of users in the waiting room (DTOs)
deactivate System

deactivate Nurse
@enduml