@startuml
hide circle
hide methods
skinparam classAttributeIconSize 0

class "DGS Administrator" {
}

class Vaccine {
  - name
  - brand
  - number_of_doses
}

class "Vaccine Type" {
  - code
  - description
  - technology
}

"DGS Administrator" "1" -right-- "*" Vaccine: manages >
Vaccine "*" -up-- "1" "Vaccine Type": has >

@enduml