@startuml
autonumber

actor "Administrator" as Admin
participant ":SpecifyVaccineTypeUI" as UI
participant ":SpecifyVaccineTypeController" as CTRL
participant ":VaccineTypeService" as SVC
participant "dto: VaccineTypeDTO" as DTO
participant ":VaccineTypeMapper" as MAPPER
participant "vt: VaccineType" as VT
participant ":VaccineTypeRepository" as REPO

activate Admin
Admin -> UI : asks to specify new vaccine type
activate UI

UI --> Admin : asks for data (code, description, technology)
deactivate UI

Admin -> UI : types data
activate UI

' UI cria o DTO
UI -> DTO** : create(code, description, technology)

UI -> CTRL : createVaccineType(dto)
activate CTRL

CTRL -> SVC : createVaccineType(dto)
activate SVC

' 1. Converter DTO para Domínio
SVC -> MAPPER : toModel(dto)
activate MAPPER
MAPPER -> VT** : create(code, description, technology)
MAPPER --> SVC : vt
deactivate MAPPER

' 2. Guardar no Repositório
SVC -> REPO : save(vt)
activate REPO
REPO --> SVC : boolean (success)
deactivate REPO

SVC --> CTRL : success
deactivate SVC

CTRL --> UI : success
deactivate CTRL

UI --> Admin : displays success message
deactivate UI

deactivate Admin
@enduml