@startuml
skinparam classAttributeIconSize 0
hide circle

class ListVaccinesUI {
}

class ListVaccinesController {
  + getVaccinesList() : List<Vaccine>
}

class Company {
  + getVaccineStore() : VaccineStore
}

class VaccineStore {
  + getVaccines() : List<Vaccine>
}

class Vaccine {
  - name
  - brand
  - type
}

ListVaccinesUI ..> ListVaccinesController
ListVaccinesController ..> Company
ListVaccinesController ..> VaccineStore

Company "1" --> "1" VaccineStore : has >
VaccineStore "1" --> "*" Vaccine : stores >

@enduml