@startuml
skinparam classAttributeIconSize 0
hide circle

class ListVaccinesUI {
}

class ListVaccinesController {
  + getVaccineList()
}

class Company {
  + getVaccineStore()
}

class VaccineStore {
  + getAll()
}

class Vaccine {
  - commercial_name
  - brand
  + getBrand()
  + getType()
}

class "Vaccine Type" {
  - code
  - short_description
}

ListVaccinesUI ..> ListVaccinesController
ListVaccinesController ..> Company
ListVaccinesController ..> VaccineStore
Company "1" --> "1" VaccineStore : has >
VaccineStore "1" --> "*" Vaccine : stores >
Vaccine "*" --> "1" "Vaccine Type" : has >

@enduml