@startuml
hide circle
hide methods
skinparam classAttributeIconSize 0

class "DGS Administrator" {
}

class Vaccine {
  - commercial_name
  - brand
}

class "Vaccine Type" {
  - code
  - short_description
}

"DGS Administrator" "1" -right-- "*" Vaccine: consults >
Vaccine "*" -down-- "1" "Vaccine Type": has >
@enduml