@startuml
autonumber
actor "Administrator" as Admin
participant ":System" as System

activate Admin

Admin -> System : asks to specify a new vaccine type
activate System
System --> Admin : asks for the data (Code, Description, Technology)
deactivate System

Admin -> System : types the requested data
activate System
System --> Admin : shows the data and requests confirmation
deactivate System

Admin -> System : confirms the data
activate System
System --> Admin : records the vaccine type and informs success
deactivate System

deactivate Admin
@enduml