@startuml
autonumber
actor "Administrator" as Admin
participant ":System" as System

activate Admin

Admin -> System : asks to register a new receptionist
activate System
System --> Admin : asks for the receptionist data (Name, Address, Phone, Email, CC Number)
deactivate System

Admin -> System : types the requested data
activate System
System --> Admin : shows the data and requests confirmation
deactivate System

Admin -> System : confirms the data
activate System
System --> Admin : registers the receptionist, generates credentials and informs success
deactivate System

deactivate Admin
@enduml