@startuml
autonumber
actor "DGS Administrator" as Admin
participant ":RegisterVaccination\nCenterUI" as UI
participant ":RegisterVaccination\nCenterController" as CTRL
participant ":Company" as CMP
participant "store\n:VaccinationCenterStore" as STORE
participant "vtStore\n:VaccineTypeStore" as VTSTORE
participant "center\n:VaccinationCenter" as CENTER

activate Admin
Admin -> UI : asks to register a new vaccination center
activate UI

UI -> CTRL : getVaccinationCenterTypes()
activate CTRL
CTRL --> UI : list of types
deactivate CTRL

UI --> Admin : requests the vaccination center type
deactivate UI

Admin -> UI : selects the type (e.g. Community Mass Vaccination Center)
activate UI

opt if selected type is CommunityMassVaccinationCenter
    UI -> CTRL : getVaccineTypes()
    activate CTRL
    CTRL -> CMP : vtStore = getVaccineTypeStore()
    activate CMP
    deactivate CMP
    CTRL -> VTSTORE : getVaccineTypes()
    activate VTSTORE
    VTSTORE --> CTRL : list of vaccine types
    deactivate VTSTORE
    CTRL --> UI : list of vaccine types
    deactivate CTRL

    UI --> Admin : requests to select the vaccine type
    Admin -> UI : selects the vaccine type
end

UI --> Admin : requests data (name, address, phone, email, website,\n open/close hours, capacity, + ARS/AGES if Healthcare)
deactivate UI

Admin -> UI : types the requested data
activate UI

UI -> CTRL : createVaccinationCenter(dto)
activate CTRL

CTRL -> CMP : store = getVaccinationCenterStore()
activate CMP
deactivate CMP

CTRL -> STORE : center = createVaccinationCenter(dto)
activate STORE

create CENTER
STORE -> CENTER : create(...)

activate CENTER
deactivate CENTER

STORE --> CTRL : center
deactivate STORE

CTRL -> STORE : validateVaccinationCenter(center)
activate STORE
deactivate STORE

CTRL --> UI : center info
deactivate CTRL

UI --> Admin : shows all data and requests confirmation
deactivate UI

Admin -> UI : confirms the data
activate UI

UI -> CTRL : save()
activate CTRL

CTRL -> STORE : saveVaccinationCenter(center)
activate STORE
    STORE -> STORE : add(center)
deactivate STORE

CTRL --> UI : result
deactivate CTRL

UI --> Admin : informs operation success
deactivate UI
deactivate Admin

@enduml