@startuml
hide circle
hide methods
skinparam classAttributeIconSize 0

class "DGS Administrator" {
}

abstract class "Vaccination Center" {
  - name
  - postal_address
  - phone_number
  - email
  - website_address
  - opening_hours
  - closing_hours
  - capacity_per_hour
}

class "Healthcare Center" {
  - ars
  - ages
}

class "Community Mass Vaccination Center" {
}

class "Vaccine Type" {
  - code
  - description
  - technology
}

class "Waiting Room" {
}

class "Recovery Room" {
}

"Healthcare Center" --|> "Vaccination Center"
"Community Mass Vaccination Center" --|> "Vaccination Center"

"DGS Administrator" "1" -right-- "0..*" "Vaccination Center": manages >

"Community Mass Vaccination Center" "1" -- "1" "Vaccine Type": administers >

"Vaccination Center" "1" *-- "1" "Waiting Room": has >
"Vaccination Center" "1" *-- "1" "Recovery Room": has >
@enduml