@startuml
autonumber

actor "Administrator" as Admin
participant ":SpecifyVaccineUI" as UI
participant ":SpecifyVaccineController" as CTRL
participant ":VaccineService" as SVC
participant ":VaccineTypeRepository" as TypeRepo
participant ":VaccineRepository" as VacRepo
participant ":VaccineMapper" as MAPPER
participant "dto: VaccineDTO" as DTO
participant "vaccine: Vaccine" as VAC

activate Admin
Admin -> UI : asks to specify new vaccine
activate UI

' 1. Obter Tipos de Vacina para seleção
UI -> CTRL : getVaccineTypes()
activate CTRL
CTRL -> SVC : getVaccineTypes()
activate SVC
SVC -> TypeRepo : findAll()
activate TypeRepo
TypeRepo --> SVC : typesList
deactivate TypeRepo
SVC --> CTRL : typesDTOList
deactivate SVC
CTRL --> UI : typesDTOList
deactivate CTRL

UI --> Admin : shows types and asks to select
deactivate UI

Admin -> UI : selects type and inputs vaccine data
activate UI

' 2. Criar a Vacina
UI -> DTO** : create(name, brand, typeCode, adminProcessData...)

UI -> CTRL : createVaccine(dto)
activate CTRL

CTRL -> SVC : createVaccine(dto)
activate SVC

' Obter a entidade VaccineType
SVC -> TypeRepo : findByCode(dto.typeCode)
activate TypeRepo
TypeRepo --> SVC : vaccineType
deactivate TypeRepo

' Converter DTO para Domínio (usando Mapper e o Tipo recuperado)
SVC -> MAPPER : toModel(dto, vaccineType)
activate MAPPER
MAPPER -> VAC** : create(name, brand, vaccineType, ...)
MAPPER --> SVC : vaccine
deactivate MAPPER

' Guardar
SVC -> VacRepo : save(vaccine)
activate VacRepo
VacRepo --> SVC : success
deactivate VacRepo

SVC --> CTRL : success
deactivate SVC

CTRL --> UI : success
deactivate CTRL

UI --> Admin : displays success message
deactivate UI

deactivate Admin
@enduml