@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Administrator {
  - name
  - email
  - phoneNumber
  - employeeId
}

class VaccineType {
  - code
  - description
  - technology
}

class Vaccine {
  - name
  - brand
  - id
}

class AdministrationProcess {
  - doseNumber
  - dosage
  - timeIntervalBetweenDoses
}

class AgeGroup {
  - minimumAge
  - maximumAge
}

' Relacionamentos
Administrator "1" -- "*" Vaccine : specifies >
Vaccine "*" -- "1" VaccineType : is of >
Vaccine "1" -- "1..*" AdministrationProcess : consists of >
AdministrationProcess "*" -- "1" AgeGroup : applicable to >

@enduml