@startuml
autonumber
actor "Administrator" as Admin
participant ":System" as System

activate Admin

Admin -> System : asks to specify a new vaccine
activate System
System --> Admin : shows list of vaccine types and asks to select one
deactivate System

Admin -> System : selects a vaccine type
activate System
System --> Admin : asks for vaccine data (Name, Brand, ID)
deactivate System

Admin -> System : types requested data
activate System
System --> Admin : asks for administration process data (Age groups, Doses, Intervals)
deactivate System

Admin -> System : types administration process data
activate System
System --> Admin : shows all data and requests confirmation
deactivate System

Admin -> System : confirms data
activate System
System --> Admin : records the vaccine and informs success
deactivate System

deactivate Admin
@enduml