@startuml
autonumber
actor "SNS User" as User
participant ":System" as System

activate User

User -> System : asks to schedule a vaccine administration
activate System
System --> User : shows list of vaccination centers and asks to select one
deactivate System

User -> System : selects a vaccination center
activate System
System --> User : shows list of vaccine types and asks to select one
deactivate System

User -> System : selects a vaccine type
activate System
System --> User : asks for preferred date and time
deactivate System

User -> System : types date and time
activate System
System --> User : validates data, shows details and asks for confirmation
deactivate System

User -> System : confirms
activate System
System --> User : records the appointment and informs success
deactivate System

deactivate User
@enduml