@startuml
'https://plantuml-server.url.net/svg/
skinparam classAttributeIconSize 0
hide circle
hide methods

class Administrator {
}

class VaccineType {
       - code
       - disease
       - short_description
}

Administrator "1" -right-- "0..*" VaccineType:  maintains >

@enduml
