@startuml
'https://plantuml.com/sequence-diagram
autoactivate on
autonumber

actor "DGS Administrator" as User
participant ":RegisterEmployeeView" as View
participant ":RegisterEmployeeController" as Ctrl
participant ":DGS Administrator" as Admin
participant "empCont:EmployeeContainer" as EmpCont
participant "emp:Employee" as Emp

activate User

User -> View: asks to register a new employee

View -> Ctrl: getRoles()
Ctrl --> View: list<String> (Nurse, Receptionist)

View --> User: requests data and role selection

User -> View: types data and selects "Nurse"
View -> Ctrl: registerEmployee(name, address, phone, email, cc, "Nurse")

Ctrl -> Admin: getEmployeeContainer()
Admin --> Ctrl: empCont
Ctrl -> EmpCont: create(name, address, phone, email, cc, "Nurse")

EmpCont -> Emp**: create(name, address, ...)
note right: Instantiates 'Nurse' or 'Receptionist' \nbased on selection
EmpCont --> Ctrl: emp
Ctrl --> View: ok

View --> User: shows all data and requests confirmation

User -> View: confirms the data

View -> Ctrl: saveEmployee()
Ctrl -> EmpCont: save(emp)
EmpCont -> EmpCont : validate(emp) ' Validação Global (email/phone unicos)
EmpCont --> EmpCont : ok
EmpCont -> EmpCont: add(emp)
EmpCont --> EmpCont : ok
EmpCont --> Ctrl: ok
Ctrl --> View: ok

View --> User: informs operation success
@enduml