@startuml
'https://plantuml-server.url.net/svg/
skinparam classAttributeIconSize 0
hide circle
hide methods

class Administrator {
}

class Employee {
    - name
    - phoneNumber
    - emailAddress
    - citizenCardNumber
}

class Role {
    - code
    - description
}

Administrator "1" -right-- "0..*" Employee:  maintains >

Employee "0..*" -left-- "1" Role:  has a >

@enduml