@startuml
'https://plantuml-server.url.net/svg/
autoactivate on
autonumber

actor "Administrator" as User
participant ":RegisterEmployeeView" as View
participant ":RegisterEmployeeController" as Ctrl
participant ":Administrator" as Admin
participant "roleCont:RoleContainer" as RoleCont
participant "empCont:EmployeeContainer" as EmpCont
participant "emp:Employee" as Emp

activate User

User -> View: asks to register a new employee

View -> Ctrl: getRoles()
Ctrl -> Admin: getRoleContainer()
Admin --> Ctrl: roleCont
Ctrl -> RoleCont: getRoles()
RoleCont --> Ctrl: list<Role>
Ctrl --> View: list<Role>

View --> User: requests data (name, phone, email, cc) and role selection

User -> View: types requested data and selects a role
View -> Ctrl: registerEmployee(name, phone, email, cc, selectedRole)

Ctrl -> Admin: getEmployeeContainer()
Admin --> Ctrl: empCont
Ctrl -> EmpCont: create(name, phone, email, cc, selectedRole)
EmpCont --> Emp**: create(name, phone, email, cc, selectedRole)
EmpCont --> Ctrl: emp
Ctrl --> View: ok

View --> User: shows all data and requests confirmation

User -> View: confirms the data

View -> Ctrl: saveEmployee()
Ctrl -> EmpCont: save(emp)
EmpCont -> EmpCont : validate(emp) ' Validação global (ex: duplicados - AC14-4)
EmpCont --> EmpCont : ok
EmpCont -> EmpCont: add(emp)
EmpCont --> EmpCont : ok
EmpCont --> Ctrl: ok
Ctrl --> View: ok

View --> User: informs operation success
@enduml