@startuml
'https://plantuml-server.url.net/svg/
skinparam classAttributeIconSize 0
hide circle
hide methods

class Administrator {
}

class Employee {
    - name
    - phoneNumber
    - emailAddress
    - citizenCardNumber
}

class Role {
    - code
    - description
}

' O Administrador mantém o registo de Empregados
Administrator "1" -right-- "0..*" Employee:  maintains >

' Cada Empregado tem obrigatoriamente um Papel (AC14-1)
Employee "0..*" -left-- "1" Role:  has a >

@enduml