@startuml
'https://plantuml.com/class-diagram

hide circle
skinparam classAttributeIconSize 0


class RegisterEmployeeView {
}

class RegisterEmployeeController {
    + getRoles(): List<String>
    + registerEmployee(name, address, phone, email, cc, roleId): void
    + saveEmployee(): Result
}


class "DGS Administrator" {
    + getEmployeeContainer(): EmployeeContainer
}

class EmployeeContainer {
    + create(name, address, phone, email, cc, roleId): Employee
    + save(Employee obj): Result
}

abstract class Employee {
    - name: string
    - postal_address: string
    - phone_number: string
    - email: string
    - citizen_card_number: string
    + Employee(name, address, phone, email, cc)
}

class Nurse {
}

class Receptionist {
}


"DGS Administrator" "1" -right-> "1" EmployeeContainer:  manages
EmployeeContainer "1" -right-> "0..*" Employee:  records

Nurse --|> Employee
Receptionist --|> Employee

RegisterEmployeeView ..> RegisterEmployeeController

RegisterEmployeeController ..> "DGS Administrator"
RegisterEmployeeController ..> EmployeeContainer
RegisterEmployeeController ..> Employee

@enduml