@startuml
autonumber
actor "Administrator" as Admin
participant ":System" as System

activate Admin

Admin -> System : asks to load SNS users from a CSV file
activate System
System --> Admin : asks for the file path/name
deactivate System

Admin -> System : types the file path
activate System
System --> Admin : validates the file and displays summary (number of users to load)
deactivate System

Admin -> System : confirms
activate System
System --> Admin : loads the users and informs operation success
deactivate System

deactivate Admin
@enduml