@startuml
hide methods
left to right direction
skinparam classAttributeIconSize 0

class Administrator {
  - name
  - email
  - phoneNumber
  - employeeId
}

class CSVFile {
  - fileName
  - filePath
  - content
  - numberOfRecords
}

class SNSUser {
  - name
  - address
  - sex
  - phoneNumber
  - email
  - birthDate
  - snsUserNumber
  - citizenCardNumber
}

' Relações
Administrator "1" -- "1" CSVFile : loads >
CSVFile "1" -- "*" SNSUser : contains data of >
Administrator "1" -- "*" SNSUser : registers >

@enduml