@startuml
autonumber
actor "SNS User" as User
participant ":ScheduleVaccineUI" as UI
participant ":ScheduleVaccine\nController" as CTRL
participant ":Company" as CMP
participant "centerStore\n:VaccinationCenterStore" as C_STORE
participant "typeStore\n:VaccineTypeStore" as T_STORE
participant "center\n:Vaccination Center" as CENTER
participant "app\n:Appointment" as APP

activate User
User -> UI : asks to schedule a vaccine administration
activate UI

'--- Selecionar Centro ---
UI -> CTRL : getVaccinationCenters()
activate CTRL
CTRL -> CMP : store = getVaccinationCenterStore()
activate CMP
deactivate CMP
CTRL -> C_STORE : getList()
activate C_STORE
deactivate C_STORE
CTRL --> UI : list of centers
deactivate CTRL

UI --> User : shows list and asks to select one
deactivate UI

User -> UI : selects a vaccination center
activate UI

'--- Selecionar Tipo de Vacina ---
UI -> CTRL : getVaccineTypes()
activate CTRL
CTRL -> CMP : typeStore = getVaccineTypeStore()
activate CMP
deactivate CMP
CTRL -> T_STORE : getList()
activate T_STORE
deactivate T_STORE
CTRL --> UI : list of types
deactivate CTRL

UI --> User : asks to select vaccine type
deactivate UI
User -> UI : selects vaccine type
activate UI

'--- Selecionar Data e Slot ---
UI --> User : requests preferred date
deactivate UI
User -> UI : types date
activate UI

UI -> CTRL : getAvailableSlots(center, date)
activate CTRL
    CTRL -> CENTER : getAvailableSlots(date)
    activate CENTER
    note right of CENTER
       Checks capacity per hour vs
       existing appointments
       for that day
    end note
    CENTER --> CTRL : list of slots
    deactivate CENTER
CTRL --> UI : list of slots
deactivate CTRL

UI --> User : shows available slots
deactivate UI

User -> UI : selects a time slot
activate UI

'--- Criar Agendamento ---
UI -> CTRL : createAppointment(dto)
activate CTRL

    CTRL -> CENTER : createAppointment(user, vaccineType, date, time)
    activate CENTER

        CENTER -> CENTER : validateSlot(date, time)

        create APP
        CENTER -> APP : create(user, vaccineType, date, time)

    CENTER --> CTRL : app
    deactivate CENTER

CTRL -> CENTER : validateAppointment(app)
activate CENTER
deactivate CENTER

CTRL --> UI : appointment info
deactivate CTRL

UI --> User : shows data and requests confirmation
deactivate UI

User -> UI : confirms
activate UI

UI -> CTRL : save()
activate CTRL
    CTRL -> CENTER : addAppointment(app)
    activate CENTER
    deactivate CENTER
CTRL --> UI : success
deactivate CTRL

UI --> User : informs operation success
deactivate UI
deactivate User

@enduml