@startuml
skinparam classAttributeIconSize 0

package "UI" {
  class LoadUsersUI {
  }
}

package "Core" {

  package "Controller" {
    class LoadUsersController {
      + loadUsers(filePath: String): int
    }
  }

  package "Service" {
    class LoadUsersService {
      + loadUsers(filePath: String): int
    }
  }

  package "Utils" {
    class CSVReader {
      + read(filePath: String): List<String[]>
    }
  }

  package "Domain" {
    package "Model" {
      class SNSUser {
        - name: String
        - snsUserNumber: String
        - email: String
        + create(...)
      }
    }

    package "Repository" {
      class SNSUserRepository {
        + save(user: SNSUser): boolean
        + findByNumber(num: String): SNSUser
      }
    }
  }

  package "DTO" {
    class SNSUserDTO {
      - name
      - snsUserNumber
      - email
    }
  }

  package "Mapper" {
    class SNSUserMapper {
      + toModel(dto: SNSUserDTO): SNSUser
    }
  }
}

LoadUsersUI ..> LoadUsersController

LoadUsersController ..> LoadUsersService

LoadUsersService ..> CSVReader
LoadUsersService ..> SNSUserRepository
LoadUsersService ..> SNSUserMapper
LoadUsersService ..> SNSUserDTO
LoadUsersService ..> SNSUser

SNSUserMapper ..> SNSUserDTO
SNSUserMapper ..> SNSUser

SNSUserRepository "1" --> "*" SNSUser : stores

@enduml