@startuml
autonumber
actor "Nurse" as Nurse
participant ":System" as System

activate Nurse

Nurse -> System : asks to record vaccine administration
activate System
System --> Nurse : asks for appointment data (e.g. SNS User number)
deactivate System

Nurse -> System : types requested data
activate System
System --> Nurse : shows appointment details and asks for vaccine data (lot number)
deactivate System

Nurse -> System : types vaccine data (lot number)
activate System
System --> Nurse : shows all data and requests confirmation
deactivate System

Nurse -> System : confirms data
activate System
System --> Nurse : records the administration and informs success
deactivate System

deactivate Nurse
@enduml