@startuml
autonumber

actor "Nurse" as Nurse
participant ":RecordAdministrationUI" as UI
participant ":VaccineAdministrationController" as CTRL
participant ":VaccineAdministrationService" as SVC
participant ":VaccineAdministrationMapper" as MAPPER
participant "dto: VaccineAdministrationDTO" as DTO
participant ":SNSUserRepository" as UserRepo
participant ":AppointmentRepository" as AppRepo
participant ":VaccineRepository" as VacRepo
participant ":VaccineAdministrationRepository" as AdminRepo
participant "admin: VaccineAdministration" as ADMIN

activate Nurse
Nurse -> UI : asks to record vaccine administration
activate UI

UI --> Nurse : asks for SNS User Number
deactivate UI

Nurse -> UI : provides SNS User Number
activate UI

UI -> CTRL : getAppointment(snsUserNumber)
activate CTRL
CTRL -> SVC : getAppointment(snsUserNumber)
activate SVC
SVC -> AppRepo : findAppointmentByUser(snsUserNumber)
activate AppRepo
AppRepo --> SVC : appointment
deactivate AppRepo
SVC --> CTRL : appointmentDTO
deactivate SVC
CTRL --> UI : appointmentDTO
deactivate CTRL

UI --> Nurse : shows appointment & asks for Vaccine Lot Number
deactivate UI

Nurse -> UI : provides Lot Number
activate UI

' Criação do DTO com os dados recolhidos na UI
UI -> DTO** : create(snsUserNumber, lotNumber, appointmentId)

UI -> CTRL : createVaccineAdministration(dto)
activate CTRL

CTRL -> SVC : createVaccineAdministration(dto)
activate SVC

' O Service usa os Repositórios para buscar as entidades de domínio
SVC -> UserRepo : findByNumber(dto.snsUserNumber)
activate UserRepo
UserRepo --> SVC : snsUser
deactivate UserRepo

SVC -> VacRepo : findByLot(dto.lotNumber)
activate VacRepo
VacRepo --> SVC : vaccine
deactivate VacRepo

SVC -> AppRepo : findById(dto.appointmentId)
activate AppRepo
AppRepo --> SVC : appointment
deactivate AppRepo

' Criação da entidade de domínio
SVC -> ADMIN** : create(snsUser, vaccine, appointment, lotNumber)

' Guardar a administração
SVC -> AdminRepo : save(admin)
activate AdminRepo
AdminRepo --> SVC : success
deactivate AdminRepo

SVC --> CTRL : success
deactivate SVC

CTRL --> UI : success
deactivate CTRL

UI --> Nurse : displays operation success
deactivate UI

deactivate Nurse
@enduml